version: "3.8"

services:
  # --- APP DB ---
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: kvack
      POSTGRES_PASSWORD: mojegeslo
      POSTGRES_DB: kvackalnica
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=4
      -c max_wal_senders=4
    networks:
      - kvacka-net

  # --- BACKEND ---
  backend:
    build:
      context: ./backend_kvackalnica
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgres://kvack:mojegeslo@db:5432/kvackalnica"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: kvack
      DB_PASSWORD: mojegeslo
      DB_NAME: kvackalnica
      PORT: 5000

      # Naloga 9:
      KAFKA_BROKERS: "kafka-broker:29092"
      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KAFKA_TOPIC_USER_EVENTS: "kvackalnica.user_events"
    depends_on:
      - db
      - kafka-broker
      - schema-registry
    volumes:
      - ./backend_kvackalnica:/app
      - ./backend_kvackalnica/uploads:/app/uploads
    networks:
      - kvacka-net

  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend_kvackalnica
      dockerfile: Dockerfile
    volumes:
      - ./frontend_kvackalnica:/app:cached
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=5173
      # po potrebi (če uporabljaš Vite) še:
      # - VITE_API_URL=http://localhost:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - kvacka-net

  # --- KAFKA (KRaft) ---
  kafka-broker:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-broker
    hostname: kafka-broker
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-broker:29093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-broker:29092,CONTROLLER://kafka-broker:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
      # Single-node nastavitve za ksqlDB
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - kvacka-net

  # --- SCHEMA REGISTRY ---
  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    container_name: schema-registry
    hostname: schema-registry
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-broker:29092"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    ports:
      - "8081:8081"
    depends_on:
      - kafka-broker
    networks:
      - kvacka-net

  # --- CASSANDRA ---
  cassandra1:
    image: cassandra:5.0
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "UserActivityCluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_SEEDS: "cassandra1"
      CASSANDRA_NUM_TOKENS: 256
      MAX_HEAP_SIZE: "1G"
      HEAP_NEWSIZE: "256M"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
    volumes:
      - cassandra_data:/var/lib/cassandra
    restart: unless-stopped
    networks:
      - kvacka-net

  # --- KAFKA CONNECT ---
  connect:
    image: confluentinc/cp-kafka-connect:7.7.0
    container_name: connect
    hostname: connect
    depends_on:
      - kafka-broker
      - schema-registry
      - cassandra1
      - db
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka-broker:29092"
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_REST_PORT: 8083

      CONNECT_GROUP_ID: "kvackalnica-connect"
      CONNECT_CONFIG_STORAGE_TOPIC: "_connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "_connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "_connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"

      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
    volumes:
      - connect_plugins:/usr/share/confluent-hub-components
    command: >
      bash -c "
        confluent-hub install --no-prompt confluentinc/kafka-connect-cassandra:latest &&
        confluent-hub install --no-prompt debezium/debezium-connector-postgresql:3.1.2 &&
        confluent-hub install --no-prompt confluentinc/kafka-connect-s3:latest &&
        /etc/confluent/docker/run
      "
    networks:
      - kvacka-net

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"     # S3 API
      - "9001:9001"     # MinIO Web UI
    environment:
      MINIO_ROOT_USER: "MinIOUser123"
      MINIO_ROOT_PASSWORD: "MinIOPassword123"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - kvacka-net

  # --- ksqlDB Server ---
  ksqldb-server:
    image: confluentinc/ksqldb-server:0.29.0
    container_name: ksqldb-server
    hostname: ksqldb-server
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: "kafka-broker:29092"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_KSQL_CONNECT_URL: "http://connect:8083"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      
      # Single-node nastavitve
      KSQL_KSQL_INTERNAL_TOPIC_REPLICAS: 1
      KSQL_KSQL_STREAMS_REPLICATION_FACTOR: 1
      KSQL_KSQL_SINK_REPLICAS: 1
    depends_on:
      - kafka-broker
      - schema-registry
      - connect
    networks:
      - kvacka-net

  # --- ksqlDB CLI ---
  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.29.0
    container_name: ksqldb-cli
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true
    networks:
      - kvacka-net

networks:
  kvacka-net:
    driver: bridge

volumes:
  pgdata:
  cassandra_data:
  connect_plugins:
  minio_data:
